name: MacOS (Intel) Vira Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  macos-library:
    runs-on: macos-13 # Updated August 2025
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up build environment
      uses: ./.github/actions/setup-build
      with:
        platform: macos
    
    - name: Configure project
      uses: ./.github/actions/configure-cmake
      with:
        platform: macos
    
    - name: Build project
      uses: ./.github/actions/build-cmake
      with:
        platform: macos